[build]
  command = "make rust && make build"
  functions = "functions/"
  publish = "public/"
[build.environment]
  GO_IMPORT_PATH = "test"

[dev]
  command = "npm run local"

[[redirects]]
  from = "/api/gotest"
  to = "/.netlify/functions/gotest"
  status = 200
  force = true

[[redirects]]
  from = "/api/rusttest"
  to = "/.netlify/functions/rusttest"
  status = 200
  force = true